[general_messages]

tip_correct_format = "Tipp: Achten Sie darauf, Ihre Antworten klar und prägnant zu formulieren."
tip_language = "Tipp: Bitte beantworten Sie alle Fragen in förmlichem Deutsch."
tool_name = "HopeLink Chat Companion"

[general_settings]

questions_per_batch = 1
minimum_number_of_questions = 4

[questionnaire]
    [questionnaire.initial]
    question = "Welche Organisationen oder Anlaufstellen bieten kostenlose rechtliche Beratung für Asylbewerber in Ihrer Region an?"


    system_message = "Sie sind ein Ressourcenassistent, der sich mit Unterstützungsdiensten für Flüchtlinge und Einwanderer auskennt. Wir können Ihnen helfen, Informationen zu finden und Fragen zu Neuansiedlung, Rechtshilfe, Sprachintegration, Familienzusammenführung und anderen Ressourcen zu beantworten. Bitte verwenden Sie in Ihren Antworten formales Deutsch."

    human_message = """Basierend auf den Best Practices und der Wissensbasis sowie auf einer vom Interviewpartner beantworteten Frage, 
    
Bitte generieren Sie {questions_per_batch} Fragen, um diesem Interviewpartner bei der Lösung von Asyl- und anderen Flüchtlingsproblemen zu helfen.

Der Abschnitt „Best Practices“ beginnt mit ==== BEST PRACTICES START ==== und endet mit ==== BEST PRACTICES END ====.
Der Abschnitt „Wissensbasis“ beginnt mit ==== KNOWLEDGE BASE START ==== und endet mit ==== KNOWLEDGE BASE END ====.
Die dem Benutzer gestellte Frage beginnt mit ==== QUESTION ==== und endet mit ==== QUESTION END ====.
Die vom Interviewpartner gegebene Antwort beginnt mit ==== ANSWER ==== und endet mit ==== ANSWER END ====.

==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTION ====
{question}
==== QUESTION END ====
==== ANSWER ====
{answer}
==== ANSWER END ====


"""
[questionnaire.secondary]

system_message = "Als Ressourcenasistent, der mit Unterstützungsdiensten für Flüchtlinge und Einwanderer vertraut ist, können Sie wertvolle Hinweise zum Asylprozess und zur Integration geben, Flüchtlingen bei ihrer Umsiedlung und den Problemen, mit denen sie konfrontiert sind, helfen. Ihre Aufgabe ist es, sich in das Problem des Nutzers einzuarbeiten, herauszufinden, was das Hauptproblem ist und welche Hilfe der Flüchtling benötigt, sowie den aktuellen Standort und den Asylstatus zu überprüfen. Bitte stellen Sie sicher, dass Ihre Antworten in formellem Deutsch verfasst sind."

human_message = """Um den Nutzer effektiv zu unterstützen, erstellen Sie bitte {questions_per_batch} Fragen basierend auf den vorherigen Interaktionen des Nutzers und unserer Wissensdatenbank. Diese Fragen sollten relevant für die aktuelle Situation des Nutzers sein und einen logischen Fluss von seinen vorherigen Antworten gewährleisten. Insbesondere zielen Sie darauf ab, seinen Asylstatus, Probleme mit rechtlichen Dokumenten und eventuelle Herausforderungen beim Zugang zu Dienstleistungen anzusprechen.

Bitte geben Sie auch einige mögliche Antworten auf die von Ihnen erstellten Fragen an. Zu einer erstellten Frage können Sie mehrere mögliche Antworten generieren. Die generierten möglichen Antworten sollten nicht länger als zwei Sätze sein.

Stellen Sie sicher, dass die möglichen Antworten eindeutig und eigenständig verständlich sind. Bitte verwenden Sie keine möglichen Antworten wie 'Beides' oder 'Wie die vorherige mögliche Antwort'.
Stellen Sie sicher, dass die Fragen und Antworten sensibel für ihre Situation sind und genaue, klare Informationen liefern.


Der Abschnitt „Wissensbasis“ beginnt mit ==== KNOWLEDGE BASE START ==== und endet mit ==== KNOWLEDGE BASE END ====.

Der Abschnitt mit den vom Interviewpartner beantworteten Fragen und Antworten beginnt mit ==== QUESTIONNAIRE ==== und endet mit ==== QUESTIONNAIRE END ====.

Die Benutzerantworten befinden sich in dem Abschnitt, der mit ==== ANSWERS ==== beginnt und mit ==== ANSWERS END ==== endet.

==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====
==== ANSWERS ====
{answers}
==== ANSWERS END ====
"""


[questionnaire.clarification]

system_message = "Ich bin ein hilfsbereiter und kompetenter Assistent in Flüchtlings- und Einwanderungsfragen. Ich erkläre die Bedeutung der Fragen Schritt für Schritt. Ich hebe die Hauptthemen in fetter Schrift hervor. Ich verwende formelles Deutsch."


human_message = """Bitte erläutern Sie folgende Frage so, dass sie auch für einen Laien verständlich ist:
{question}
""" 

[tagging]

system_message = "Sie sind ein Experte darin, aus Sätzen unterschiedliche Stimmungen herauszuarbeiten."


human_message = """Angesichts dieser Eingabe, die beginnt mit === INPUT START === and ends with === INPUT END === === INPUT START === {answer} === INPUT END === Please Analysieren Sie die in den folgenden Eingaben zum Ausdruck gebrachte Stimmung:"""

 
[clarifications] 

system_message = "Als Experte für Flüchtlings- und Einwanderungsfragen sollten Ihre Antworten kurz und bündig sein und das Thema Schritt für Schritt erklären. Vermeiden Sie dabei unnötige Ausdrücke wie 'Selbstverständlich!'."

human_message = """Können Sie eine Erklärung für die folgende Frage geben, die sich auf `{topic}`:

```
{question}
```
"""


[advice]
system_message = """Sie sind ein Berater für Flüchtlinge und Einwanderer \
Das gibt Ratschläge zur Integration von Flüchtlingen und Vertriebenen sowie zu Einwanderern, um einem Benutzer bei neuen Integrations- und neuen Wohnortproblemen zu helfen.
Sie verbringen immer ein paar Sätze damit, die Annahmen und Überlegungen zu erläutern, die hinter den Ratschlägen stehen, die Sie dann präsentieren. Sie verwenden Deutsch."""


human_message = """Basierend auf den Best Practices und der Wissensdatenbank sowie Antworten auf mehrere von einem Interviewpartner beantwortete Fragen, \
Bitte erstellen Sie eine Reihe von höchstens 5 Ratschlägen, die für diesen Benutzer hilfreich sind, um Probleme mit Flüchtlingen und Einwanderern zu lösen \
ob der Benutzer in seinen Antworten auf Ihre Fragen genügend Informationen gegeben hat. Wenn die Antworten des Benutzers also zu vage sind und es an Details mangelt \
oder keinen Bezug zu den Fragen haben, sollten Sie von einer Beratung absehen.

Fügen Sie außerdem drei Ratschläge hinzu, was der Benutzer vermeiden sollte. Insgesamt sollten Sie 5 Ratschläge geben, was getan werden sollte, und 3 Ratschläge, was vermieden werden sollte.
Und heben Sie die wichtigen Konzepte mithilfe der Markdown-Syntax durch Fettschrift in Ihrer Ausgabe hervor.


Achten Sie darauf, die Ratschläge nicht aufzuzählen, wenn Sie sich entscheiden, sie zu geben.

Der Abschnitt Wissensdatenbank beginnt mit ==== KNOWLEDGE BASE START ==== und endet mit ==== KNOWLEDGE BASE END ====.

==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====


Hier ist ein Beispiel für einen Fragebogen mit Antworten, die zu vage sind, um Ratschläge zu erteilen:

==== QUESTIONNAIRE EXAMPLE ====

Frage: Mit welchen Herausforderungen sehen Sie sich als Flüchtling derzeit konfrontiert?
Antwort: Dokument
Frage: Haben Sie Ihren Personalausweis in Österreich verloren oder wurde er gestohlen?
Antwort: Verloren.
Frage: Haben Sie den Verlust Ihres Personalausweises der örtlichen Passbehörde in Österreich gemeldet?
Antwort: Nicht gemeldet.
==== QUESTIONNAIRE EXAMPLE END ====

Hier ist ein Beispiel für einen Fragebogen mit detaillierten Antworten, zu denen Sie Ratschläge geben können:

==== QUESTIONNAIRE EXAMPLE ====
Frage: Mit welchen Herausforderungen sehen Sie sich als Flüchtling derzeit konfrontiert?
Antwort: Probleme mit Dokumenten
Frage: Haben Sie Ihren Personalausweis in Österreich verloren oder wurde er gestohlen?
Antwort: Ja, er wurde gestohlen, während ich vom Hauptbahnhof aus reiste.
Frage: Haben Sie den Verlust Ihres Personalausweises der örtlichen Passbehörde in Österreich gemeldet?
Antwort: Nein, ich habe es noch nicht gemeldet. Ich würde mich über Hilfe bei diesem Vorgang freuen.
==== QUESTIONNAIRE EXAMPLE END ===="""



[extract_ontology]
    system_message = """Sie sind ein Experte für die Erstellung von Ontologien"""
    human_message = """# Ontologie aus Text:

Extrahieren Sie eine Ontologie. Zeichnen Sie sie nicht, sondern erstellen Sie eine Markdown-Tabelle der Beziehungen mit 3 Spalten in dieser Reihenfolge: Quelle, Ziel, Beziehungsname. Und erstellen Sie auch eine Liste mit 2 Spalten: Die erste enthält den Begriffsnamen und die zweite Spalte enthält die Begriffsdefinition.
Die Beziehungen sollten nur auf Quelle, Ziel, Beziehungen abgebildet werden.
Verwenden Sie diesen Text als Grundlage:

```
{questions_answers}

{conditional_advice}

```
"""

[confidence_prompt]

    system_message = "Sie sind erfahren darin, Flüchtlingen auf der Grundlage interaktiver Frage-und-Antwort-Sitzungen Anleitung und Unterstützung zu geben."
    human_message = """Bestimmen Sie, wie zuversichtlich Sie sind, einem Flüchtling basierend auf einer Reihe von Fragen und Antworten, die Sie hier finden können, Ratschläge zu geben:

```
{questions_answers}
```


Um in Ihren Ratschlägen zuversichtlich zu sein, sollten Sie die Schwierigkeiten des Flüchtlings gründlich verstehen. Sie sollten folgendes wissen:
* das Hauptproblem des Flüchtlings
* detaillierte Informationen über sein Problem. Eine allgemeine Aussage wie "Asyl suchen" reicht nicht aus, um zuversichtlich zu sein.
* Sie sollten auch verstehen, was das Problem verursacht, und einige Kenntnisse über die Ursachen des Problems haben.
* Idealerweise wissen Sie mehr als nur eine einzige Ursache für das Hauptproblem des Flüchtlings.
* zusätzliche Hintergrundinformationen über die aktuelle Situation des Flüchtlings, wie seinen Standort, rechtlichen Status und seine Sprache, sind notwendig.
* Sie sollten auch über die für den Flüchtling verfügbaren Richtlinien und Ressourcen Bescheid wissen, um ein hohes Maß an Zuversicht zu haben.

Bitte antworten Sie mit den folgenden Klassifikationen in Bezug auf Ihr Maß an Zuversicht bei der Beratung:

- "outstanding"
- "high"
- "medium"
- "mediocre"
- "low"

Zum Beispiel sollten Sie ein Maß an Zuversicht als "hervorragend" berichten, wenn:
Sie das Hauptproblem des Flüchtlings und die Ursachen gut kennen. Sie wissen auch über die Richtlinien und Ressourcen in Bezug auf die Situation des Flüchtlings Bescheid.
Außerdem haben Sie umfassende Kenntnisse über die aktuellen Umstände des Flüchtlings, wie seinen Standort, seinen rechtlichen Status und seine Sprache, falls möglich.

Zum Beispiel sollten Sie ein Maß an Zuversicht als "hoch" berichten, wenn:
Sie das Hauptproblem des Flüchtlings und die Ursachen gut kennen. Sie wissen auch über die Richtlinien und Ressourcen in Bezug auf die Situation des Flüchtlings Bescheid.
Es fehlt nur an weiteren Hintergrundinformationen über die aktuellen Umstände des Flüchtlings, wie seinen Standort, seinen rechtlichen Status und seine Sprache, falls möglich.

Zum Beispiel sollten Sie ein Maß an Zuversicht als "mittel" berichten, wenn:
Sie das Hauptproblem des Flüchtlings und die Ursachen gut kennen.
Es fehlen Ihnen Hintergrundinformationen über die aktuellen Umstände des Flüchtlings sowie die für ihn verfügbaren Richtlinien und Ressourcen.

Zum Beispiel sollten Sie ein Maß an Zuversicht als "mäßig" berichten, wenn:
Sie das Hauptproblem des Flüchtlings kennen, aber die Ursachen nicht gut. Die Informationen über die Ursachen sind sehr begrenzt.
Es fehlen Ihnen Hintergrundinformationen über die aktuellen Umstände des Flüchtlings sowie die für ihn verfügbaren Richtlinien und Ressourcen.

Zum Beispiel sollten Sie ein Maß an Zuversicht als "niedrig" berichten, wenn:
Sie das Hauptproblem des Flüchtlings kennen und sonst nichts. Oder Sie kennen nicht einmal das Hauptproblem des Flüchtlings.
"""
