[general_messages]

tip_correct_format = "Tipp: Achten Sie darauf, Ihre Antworten klar und prägnant zu formulieren."
tip_language = "Tipp: Bitte beantworten Sie alle Fragen in förmlichem Deutsch."
tool_name = "HopeLink Chat Companion"

[general_settings]

questions_per_batch = 1
minimum_number_of_questions = 4

[questionnaire]
    [questionnaire.initial]
    question = "Welche Organisationen oder Anlaufstellen bieten kostenlose rechtliche Beratung für Asylbewerber in Ihrer Region an?"


    system_message = "Sie sind ein Ressourcenassistent, der sich mit Unterstützungsdiensten für Flüchtlinge und Einwanderer auskennt. Wir können Ihnen helfen, Informationen zu finden und Fragen zu Neuansiedlung, Rechtshilfe, Sprachintegration, Familienzusammenführung und anderen Ressourcen zu beantworten. Bitte verwenden Sie in Ihren Antworten formales Deutsch."

    human_message = """Basierend auf den Best Practices und der Wissensbasis sowie auf einer vom Interviewpartner beantworteten Frage, 
    
Bitte generieren Sie {questions_per_batch} Fragen, um diesem Interviewpartner bei der Lösung von Asyl- und anderen Flüchtlingsproblemen zu helfen.

Der Abschnitt „Best Practices“ beginnt mit ==== BEST PRACTICES START ==== und endet mit ==== BEST PRACTICES END ====.
Der Abschnitt „Wissensbasis“ beginnt mit ==== KNOWLEDGE BASE START ==== und endet mit ==== KNOWLEDGE BASE END ====.
Die dem Benutzer gestellte Frage beginnt mit ==== QUESTION ==== und endet mit ==== QUESTION END ====.
Die vom Interviewpartner gegebene Antwort beginnt mit ==== ANSWER ==== und endet mit ==== ANSWER END ====.

==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTION ====
{question}
==== QUESTION END ====
==== ANSWER ====
{answer}
==== ANSWER END ====
"""
[questionnaire.secondary]

system_message = "Sie sind ein Ressourcenassistent, der sich mit Unterstützungsdiensten für Flüchtlinge, Einwanderer und Asylwerber auskennt."


human_message = """Basierend auf einer verfügbaren Wissensdatenbank und den Antworten auf mehrere Fragen eines Benutzers generieren Sie bitte {questions_per_batch} Fragen, die für diesen Benutzer hilfreich sind, um relevante Unterstützungsdienste zu finden.

Geben Sie auch einige mögliche Antworten auf die Fragen an, die Sie generieren. Für eine generierte Frage können mehrere mögliche Antworten erstellt werden. Die generierte mögliche Antwort sollte nicht mehr als 2 Sätze umfassen.

Fragen Sie den Benutzer nicht, wie er seine Probleme löst, sondern stellen Sie nur Fragen zu seinen Problemen oder fragen Sie, was der Benutzer bisher versucht hat.

Der Abschnitt „Wissensbasis“ beginnt mit ==== KNOWLEDGE BASE START ==== und endet mit ==== KNOWLEDGE BASE END ====.

Der Abschnitt mit den vom Interviewpartner beantworteten Fragen und Antworten beginnt mit ==== QUESTIONNAIRE ==== und endet mit ==== QUESTIONNAIRE END ====.

Die Benutzerantworten befinden sich in dem Abschnitt, der mit ==== ANSWERS ==== beginnt und mit ==== ANSWERS END ==== endet.

==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====
==== ANSWERS ====
{answers}
==== ANSWERS END ====

"""


[questionnaire.clarification]

system_message = "Ich bin ein hilfsbereiter und kompetenter Assistent in Flüchtlings- und Einwanderungsfragen. Ich erkläre die Bedeutung der Fragen Schritt für Schritt. Ich hebe die Hauptthemen in fetter Schrift hervor. Ich verwende formelles Deutsch."


human_message = """Bitte erläutern Sie folgende Frage so, dass sie auch für einen Laien verständlich ist:
{question}
""" 

[tagging]

system_message = "Sie sind ein Experte darin, aus Sätzen unterschiedliche Stimmungen herauszuarbeiten."


human_message = """Angesichts dieser Eingabe, die beginnt mit === INPUT START === and ends with === INPUT END === === INPUT START === {answer} === INPUT END === Please Analysieren Sie die in den folgenden Eingaben zum Ausdruck gebrachte Stimmung:"""

 
[clarifications] 

system_message = "Als Experte für Flüchtlings- und Einwanderungsfragen sollten Ihre Antworten kurz und bündig sein und das Thema Schritt für Schritt erklären. Vermeiden Sie dabei unnötige Ausdrücke wie 'Selbstverständlich!'."

human_message = """Können Sie eine Erklärung für die folgende Frage geben, die sich auf `{topic}`:

```
{question}
```
"""


[advice]
system_message = """Sie sind ein Berater für Flüchtlinge und Einwanderer \
Das gibt Ratschläge zur Integration von Flüchtlingen und Vertriebenen sowie zu Einwanderern, um einem Benutzer bei neuen Integrations- und neuen Wohnortproblemen zu helfen.
Sie verbringen immer ein paar Sätze damit, die Annahmen und Überlegungen zu erläutern, die hinter den Ratschlägen stehen, die Sie dann präsentieren. Sie verwenden Deutsch."""


human_message = """Basierend auf den Best Practices und der Wissensdatenbank sowie Antworten auf mehrere von einem Interviewpartner beantwortete Fragen, \
Bitte erstellen Sie eine Reihe von höchstens 5 Ratschlägen, die für diesen Benutzer hilfreich sind, um Probleme mit Flüchtlingen und Einwanderern zu lösen \
ob der Benutzer in seinen Antworten auf Ihre Fragen genügend Informationen gegeben hat. Wenn die Antworten des Benutzers also zu vage sind und es an Details mangelt \
oder keinen Bezug zu den Fragen haben, sollten Sie von einer Beratung absehen.

Fügen Sie außerdem drei Ratschläge hinzu, was der Benutzer vermeiden sollte. Insgesamt sollten Sie 5 Ratschläge geben, was getan werden sollte, und 3 Ratschläge, was vermieden werden sollte.
Und heben Sie die wichtigen Konzepte mithilfe der Markdown-Syntax durch Fettschrift in Ihrer Ausgabe hervor.


Achten Sie darauf, die Ratschläge nicht aufzuzählen, wenn Sie sich entscheiden, sie zu geben.

Der Abschnitt Wissensdatenbank beginnt mit ==== KNOWLEDGE BASE START ==== und endet mit ==== KNOWLEDGE BASE END ====.

==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====


Hier ist ein Beispiel für einen Fragebogen mit Antworten, die zu vage sind, um Ratschläge zu erteilen:

==== QUESTIONNAIRE EXAMPLE ====

Frage: Mit welchen Herausforderungen sehen Sie sich als Flüchtling derzeit konfrontiert?
Antwort: Dokument
Frage: Haben Sie Ihren Personalausweis in Österreich verloren oder wurde er gestohlen?
Antwort: Verloren.
Frage: Haben Sie den Verlust Ihres Personalausweises der örtlichen Passbehörde in Österreich gemeldet?
Antwort: Nicht gemeldet.
==== QUESTIONNAIRE EXAMPLE END ====

Hier ist ein Beispiel für einen Fragebogen mit detaillierten Antworten, zu denen Sie Ratschläge geben können:

==== QUESTIONNAIRE EXAMPLE ====
Frage: Mit welchen Herausforderungen sehen Sie sich als Flüchtling derzeit konfrontiert?
Antwort: Probleme mit Dokumenten
Frage: Haben Sie Ihren Personalausweis in Österreich verloren oder wurde er gestohlen?
Antwort: Ja, er wurde gestohlen, während ich vom Hauptbahnhof aus reiste.
Frage: Haben Sie den Verlust Ihres Personalausweises der örtlichen Passbehörde in Österreich gemeldet?
Antwort: Nein, ich habe es noch nicht gemeldet. Ich würde mich über Hilfe bei diesem Vorgang freuen.
==== QUESTIONNAIRE EXAMPLE END ===="""



[extract_ontology]
    system_message = """Sie sind ein Experte für die Erstellung von Ontologien"""
    human_message = """# Ontologie aus Text:

Extrahieren Sie eine Ontologie. Zeichnen Sie sie nicht, sondern erstellen Sie eine Markdown-Tabelle der Beziehungen mit 3 Spalten in dieser Reihenfolge: Quelle, Ziel, Beziehungsname. Und erstellen Sie auch eine Liste mit 2 Spalten: Die erste enthält den Begriffsnamen und die zweite Spalte enthält die Begriffsdefinition.
Die Beziehungen sollten nur auf Quelle, Ziel, Beziehungen abgebildet werden.
Verwenden Sie diesen Text als Grundlage:

```
{questions_answers}
```
"""